### PR TITLE
[Task-3] Added handlers for getProductsById getProductsList and serverless config

### PR DESCRIPTION
**Pull request by dnegometyanov**

### CODE REVIEW

**Comment by dnegometyanov** [comment]
## Done ( so far ):
### The backend only part

    - both handlers for getProductsList and getProductsById 

    - serverless config for them

    - separated to 2 files

### TODO: Some required staff like FE integration / more code structuring and unit tests

#Links
Products List: https://gxyv76gujc.execute-api.us-east-1.amazonaws.com/dev/product

Get Products By Id: https://gxyv76gujc.execute-api.us-east-1.amazonaws.com/dev/product/7567ec4b-b10c-48c5-9345-fc73c48a80a3

Product not found (404): https://gxyv76gujc.execute-api.us-east-1.amazonaws.com/dev/product/some-fake-id

**Comment by barnardnicholas** [comment]
Reviewed - Task 1-3 completed

**Comment by VittalQSC** [comment]
**What was done**

Tasks
+3 The getProductsById AND getProductsList lambda functions return a correct response code (POINT2)

Additional tasks:
+1 Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase.
+1 Main error scenarios are handled by API ("Product not found" error).

Total score: 5

**Comment by tuwhoo** [comment]
Reviewed.
Score: 5

**Pull request merged**
